const QUESTIONS = [
  {
    question:
      "Which keyword is used to declare a block-scoped variable in JavaScript?",
    options: ["var", "let", "const", "define"],
    answer: 1,
    explanation: "let declares a variable that is limited to block scope.",
  },
  {
    question: "What is the result of typeof [] in JavaScript?",
    options: ["array", "object", "list", "undefined"],
    answer: 1,
    explanation: "Arrays are a special type of object in JavaScript.",
  },
  {
    question: "Which operator checks both value and type for equality?",
    options: ["==", "=", "===", "!="],
    answer: 2,
    explanation: "=== compares both value and type.",
  },
  {
    question: "How do you get the length of a string stored in variable str?",
    options: ["str.size", "length(str)", "str.length()", "str.length"],
    answer: 3,
    explanation: "Strings use the length property, not a function.",
  },
  {
    question: "Which method adds a new element to the end of an array?",
    options: ["push()", "add()", "append()", "insert()"],
    answer: 0,
    explanation: "push() adds one or more elements to the end of an array.",
  },
  {
    question: "Which method removes the last element from an array?",
    options: ["shift()", "remove()", "pop()", "delete()"],
    answer: 2,
    explanation: "pop() removes and returns the last element.",
  },
  {
    question: "How do you access the first element of an array named arr?",
    options: ["arr.first()", "arr[1]", "arr[0]", "arr.get(0)"],
    answer: 2,
    explanation: "Array indexing starts from 0.",
  },
  {
    question: "Which function converts a string to an integer?",
    options: ["Number()", "parseInt()", "toInt()", "Math.int()"],
    answer: 1,
    explanation: "parseInt() parses a string and returns an integer.",
  },
  {
    question: "What does NaN stand for in JavaScript?",
    options: [
      "No assigned Number",
      "Not a Name",
      "Not a Number",
      "Null as Number",
    ],
    answer: 2,
    explanation: "NaN means Not a Number.",
  },
  {
    question: "What is the main purpose of console.log()?",
    options: [
      "Display alerts",
      "Log data for debugging",
      "Create variables",
      "Stop code execution",
    ],
    answer: 1,
    explanation: "console.log() prints values to the console for debugging.",
  },
  {
    question: "Which of these variables cannot be reassigned?",
    options: ["var", "let", "const", "function"],
    answer: 2,
    explanation: "const variables cannot be reassigned.",
  },
  {
    question: "What is returned when accessing a non-existing object property?",
    options: ["null", "false", "0", "undefined"],
    answer: 3,
    explanation: "Undefined is returned for missing properties.",
  },
  {
    question: "Which loop is best when you know how many times to iterate?",
    options: ["while", "do...while", "for", "foreach"],
    answer: 2,
    explanation: "for loops are ideal for a known number of iterations.",
  },
  {
    question: "Which symbol is used in arrow functions?",
    options: ["->", "=>", "::", "<-"],
    answer: 1,
    explanation: "Arrow functions use the => syntax.",
  },
  {
    question: "What does Math.floor(4.9) return?",
    options: ["5", "4", "4.9", "0"],
    answer: 1,
    explanation: "Math.floor rounds down to the nearest integer.",
  },
  {
    question: "What does JSON.stringify() do?",
    options: [
      "Parses JSON",
      "Creates a JSON file",
      "Converts an object to a JSON string",
      "Validates JSON",
    ],
    answer: 2,
    explanation: "It converts a JavaScript object into a JSON string.",
  },
  {
    question: "What does JSON.parse() do?",
    options: [
      "Converts JSON to an object",
      "Validates JSON",
      "Formats JSON",
      "Deletes JSON",
    ],
    answer: 0,
    explanation: "It converts a JSON string into a JavaScript object.",
  },
  {
    question: "Which of these values is falsy in JavaScript?",
    options: ["'0'", "[]", "0", "{}"],
    answer: 2,
    explanation: "0 is considered a falsy value.",
  },
  {
    question: "What is the result of true && false?",
    options: ["true", "false", "null", "undefined"],
    answer: 1,
    explanation: "Both values must be true for && to return true.",
  },
  {
    question: "What happens to array length after using push() once?",
    options: [
      "It decreases by 1",
      "It stays the same",
      "It increases by 1",
      "It becomes undefined",
    ],
    answer: 2,
    explanation: "push() adds one element, increasing length by 1.",
  },
  {
    question: "What does setTimeout() do?",
    options: [
      "Repeats code execution",
      "Stops code execution",
      "Delays code execution",
      "Runs code immediately",
    ],
    answer: 2,
    explanation: "setTimeout runs code after a delay.",
  },
  {
    question: "What is the scope of variables declared with let?",
    options: ["Global", "Function", "Block", "Module"],
    answer: 2,
    explanation: "let variables are block-scoped.",
  },
  {
    question: "Which operator is commonly used to join strings?",
    options: ["", "&", "+", "%"],
    answer: 2,
    explanation: "The + operator concatenates strings.",
  },
  {
    question: "Which notation allows dynamic access to object properties?",
    options: [
      "Dot notation",
      "Bracket notation",
      "Colon notation",
      "Arrow notation",
    ],
    answer: 1,
    explanation: "Bracket notation allows dynamic property names.",
  },
  {
    question: "When is the condition checked in a while loop?",
    options: [
      "After each iteration",
      "Before each iteration",
      "Only once",
      "Never",
    ],
    answer: 1,
    explanation: "The condition is checked before each loop run.",
  },
  {
    question: "What does the break statement do in a loop?",
    options: [
      "Skips one iteration",
      "Ends the loop",
      "Restarts the loop",
      "Pauses the loop",
    ],
    answer: 1,
    explanation: "break exits the loop immediately.",
  },
  {
    question: "What does the continue statement do in a loop?",
    options: [
      "Ends the loop",
      "Skips to the next iteration",
      "Restarts the loop",
      "Stops execution",
    ],
    answer: 1,
    explanation: "continue skips the current iteration.",
  },
  {
    question: "What is the main difference between == and ===?",
    options: [
      "== checks type only",
      "=== allows coercion",
      "== allows type coercion",
      "They are identical",
    ],
    answer: 2,
    explanation: "== performs type coercion, === does not.",
  },
  {
    question: "What is the result of typeof null?",
    options: ["null", "undefined", "object", "number"],
    answer: 2,
    explanation: "typeof null returns 'object' due to a legacy behavior.",
  },
  {
    question: "What does toUpperCase() do to a string?",
    options: [
      "Changes the original string",
      "Returns a new uppercase string",
      "Deletes the string",
      "Converts to lowercase",
    ],
    answer: 1,
    explanation: "Strings are immutable, so a new string is returned.",
  },
  {
    question: "What does indexOf() return if the value is not found?",
    options: ["0", "null", "-1", "undefined"],
    answer: 2,
    explanation: "indexOf returns -1 when no match is found.",
  },
  {
    question: "Which method checks if a value is an array?",
    options: ["isArray()", "Array.isArray()", "typeof", "instanceof Array()"],
    answer: 1,
    explanation: "Array.isArray() correctly checks for arrays.",
  },
  {
    question: "What does the spread operator (...) do with arrays?",
    options: [
      "Deletes items",
      "Copies or expands elements",
      "Sorts items",
      "Filters items",
    ],
    answer: 1,
    explanation: "It expands array elements into a new array.",
  },
  {
    question: "What is destructuring used for?",
    options: [
      "Deleting variables",
      "Extracting values from arrays or objects",
      "Looping arrays",
      "Sorting objects",
    ],
    answer: 1,
    explanation: "Destructuring extracts values into variables.",
  },
  {
    question: "What does a function return if there is no return statement?",
    options: ["null", "false", "0", "undefined"],
    answer: 3,
    explanation: "Functions return undefined by default.",
  },
  {
    question: "What does 'use strict' do?",
    options: [
      "Improves performance",
      "Enables strict syntax rules",
      "Disables errors",
      "Formats code",
    ],
    answer: 1,
    explanation: "Strict mode enforces safer JavaScript rules.",
  },
  {
    question: "Which function parses a string into a floating-point number?",
    options: ["parseInt()", "Number()", "parseFloat()", "Math.float()"],
    answer: 2,
    explanation: "parseFloat converts a string to a decimal number.",
  },
  {
    question: "What range does Math.random() return?",
    options: ["1 to 10", "0 to 1", "0 to 100", "-1 to 1"],
    answer: 1,
    explanation: "It returns a number between 0 (inclusive) and 1 (exclusive).",
  },
  {
    question: "What does new Date() create?",
    options: [
      "A timestamp only",
      "The current date and time",
      "A string date",
      "A number date",
    ],
    answer: 1,
    explanation: "It creates a Date object for the current time.",
  },
  {
    question: "Which of these is a truthy value?",
    options: ["0", "null", "''", "'0'"],
    answer: 3,
    explanation: "Non-empty strings are truthy.",
  },
  {
    question: "What does the ++ operator do?",
    options: [
      "Decreases a value by 1",
      "Increases a value by 1",
      "Doubles a value",
      "Resets a value",
    ],
    answer: 1,
    explanation: "++ increments a value by 1.",
  },
  {
    question: "What does the -- operator do?",
    options: [
      "Increases a value",
      "Multiplies a value",
      "Decreases a value by 1",
      "Deletes a value",
    ],
    answer: 2,
    explanation: "It decrements a value by 1.",
  },
  {
    question: "How do you write a single-line comment in JavaScript?",
    options: ["<!-- -->", "#", "//", "/ /"],
    answer: 2,
    explanation: "// is used for single-line comments.",
  },
  {
    question: "How do you write a multi-line comment in JavaScript?",
    options: ["// comment //", "<!-- -->", "/ comment /", "# comment #"],
    answer: 2,
    explanation: "/ */ is used for multi-line comments.",
  },
  {
    question: "Which operator is used in a ternary expression?",
    options: ["&&", "::", "?:", "??"],
    answer: 2,
    explanation: "The ternary operator uses ? and :.",
  },
  {
    question: "What does Array.map() return?",
    options: [
      "A single value",
      "A modified original array",
      "A new array",
      "Nothing",
    ],
    answer: 2,
    explanation: "map returns a new array.",
  },
  {
    question: "What does a for...of loop iterate over?",
    options: ["Indexes only", "Object keys", "Iterable values", "Functions"],
    answer: 2,
    explanation: "for...of iterates over values.",
  },
  {
    question: "What does Object.keys() return?",
    options: [
      "Object values",
      "Object methods",
      "An array of keys",
      "A string",
    ],
    answer: 2,
    explanation: "It returns an array of object property names.",
  },
  {
    question: "What is try...catch used for?",
    options: [
      "Looping code",
      "Handling errors",
      "Declaring variables",
      "Creating functions",
    ],
    answer: 1,
    explanation: "try...catch is used to handle runtime errors.",
  },
  {
    question: "Which keyword is used to define a function in JavaScript?",
    options: ["method", "function", "def", "func"],
    answer: 1,
    explanation: "Functions are declared using the function keyword.",
  },
  {
    question: "What is the default value of an uninitialized variable?",
    options: ["null", "0", "undefined", "false"],
    answer: 2,
    explanation: "Variables without assigned values are undefined.",
  },
  {
    question: "Which method removes the first element from an array?",
    options: ["pop()", "shift()", "splice()", "unshift()"],
    answer: 1,
    explanation: "shift() removes the first array element.",
  },
  {
    question: "Which method adds an element to the beginning of an array?",
    options: ["push()", "append()", "unshift()", "insert()"],
    answer: 2,
    explanation: "unshift() adds elements to the start of an array.",
  },
  {
    question: "What does typeof function() {} return?",
    options: ["object", "function", "method", "undefined"],
    answer: 1,
    explanation: "Functions have the type 'function'.",
  },
  {
    question:
      "Which symbol is used to access object properties with dot notation?",
    options: [".", ":", "#", "@"],
    answer: 0,
    explanation: "Dot notation uses a period to access properties.",
  },
  {
    question: "What does alert() do?",
    options: [
      "Logs data to console",
      "Shows a popup message",
      "Stops script execution",
      "Reads user input",
    ],
    answer: 1,
    explanation: "alert() displays a popup message to the user.",
  },
  {
    question: "Which function is used to read user input from a popup?",
    options: ["alert()", "confirm()", "input()", "prompt()"],
    answer: 3,
    explanation: "prompt() displays a dialog for user input.",
  },
  {
    question: "What does confirm() return when the user clicks OK?",
    options: ["'OK'", "1", "true", "false"],
    answer: 2,
    explanation: "confirm() returns true when OK is clicked.",
  },
  {
    question: "Which value represents an empty object?",
    options: ["[]", "{}", "null", "undefined"],
    answer: 1,
    explanation: "{} represents an empty object.",
  },
  {
    question: "Which array method changes the original array?",
    options: ["map()", "filter()", "slice()", "splice()"],
    answer: 3,
    explanation: "splice() modifies the original array.",
  },
  {
    question: "What does slice() return when used on an array?",
    options: ["A new array", "The original array", "A number", "Undefined"],
    answer: 0,
    explanation: "slice() returns a new array.",
  },
  {
    question: "Which operator is used to assign a value?",
    options: ["==", "=", "===", "=>"],
    answer: 1,
    explanation: "The = operator assigns values.",
  },
  {
    question: "What does Boolean('hello') return?",
    options: ["false", "0", "true", "null"],
    answer: 2,
    explanation: "Non-empty strings are truthy.",
  },
  {
    question: "What will typeof NaN return?",
    options: ["NaN", "undefined", "number", "object"],
    answer: 2,
    explanation: "NaN is considered a number type.",
  },
  {
    question: "Which loop runs at least once even if the condition is false?",
    options: ["for", "while", "do...while", "foreach"],
    answer: 2,
    explanation: "do...while executes before checking the condition.",
  },
  {
    question: "What does Array.filter() return?",
    options: [
      "A single value",
      "A boolean",
      "A new array",
      "The original array",
    ],
    answer: 2,
    explanation: "filter() returns a new array of matching items.",
  },
  {
    question: "Which method converts an array to a string?",
    options: [
      "join()",
      "stringify()",
      "toString()",
      "Both join() and toString()",
    ],
    answer: 3,
    explanation: "Both methods convert arrays to strings.",
  },
  {
    question: "What does the length property of an empty array return?",
    options: ["null", "undefined", "1", "0"],
    answer: 3,
    explanation: "An empty array has length 0.",
  },
  {
    question: "Which statement is used to handle multiple conditions?",
    options: ["if", "else", "switch", "loop"],
    answer: 2,
    explanation: "switch handles multiple conditions.",
  },
  {
    question: "What does the logical OR (||) operator return?",
    options: [
      "True only if both are true",
      "First truthy value",
      "Always true",
      "Last false value",
    ],
    answer: 1,
    explanation: "|| returns the first truthy value.",
  },
  {
    question: "Which value is NOT a primitive type?",
    options: ["string", "number", "object", "boolean"],
    answer: 2,
    explanation: "Objects are non-primitive types.",
  },
  {
    question: "What does const prevent?",
    options: [
      "Changing object properties",
      "Reassigning the variable",
      "Using the variable",
      "Declaring variables",
    ],
    answer: 1,
    explanation: "const prevents reassignment.",
  },
  {
    question: "Which method checks if a string contains a value?",
    options: ["has()", "includes()", "index()", "contains()"],
    answer: 1,
    explanation: "includes() checks for substring existence.",
  },
  {
    question: "What does Number('10') return?",
    options: ["'10'", "NaN", "10", "undefined"],
    answer: 2,
    explanation: "Number() converts strings to numbers when possible.",
  },
  {
    question: "Which operator negates a boolean value?",
    options: ["&&", "||", "!", "~"],
    answer: 2,
    explanation: "! reverses boolean values.",
  },
  {
    question: "What does Object.values() return?",
    options: [
      "An object",
      "A string",
      "An array of values",
      "An array of keys",
    ],
    answer: 2,
    explanation: "Object.values() returns property values.",
  },
  {
    question: "Which array method is used to find one matching element?",
    options: ["filter()", "map()", "find()", "some()"],
    answer: 2,
    explanation: "find() returns the first matching element.",
  },
  {
    question: "What does some() return?",
    options: ["An array", "A number", "A boolean", "An object"],
    answer: 2,
    explanation: "some() returns true or false.",
  },
  {
    question: "What does every() check?",
    options: [
      "If any item matches",
      "If all items match",
      "If items exist",
      "If array is empty",
    ],
    answer: 1,
    explanation: "every() checks all elements.",
  },
  {
    question: "What is the purpose of return in a function?",
    options: [
      "Stop execution only",
      "Send a value back",
      "Declare variables",
      "Log output",
    ],
    answer: 1,
    explanation: "return sends a value back to the caller.",
  },
  {
    question: "What does isNaN('abc') return?",
    options: ["false", "true", "null", "0"],
    answer: 1,
    explanation: "'abc' cannot be converted to a number.",
  },
  {
    question: "Which built-in object handles math operations?",
    options: ["Number", "Calc", "Math", "Arithmetic"],
    answer: 2,
    explanation: "Math provides math-related methods.",
  },
  {
    question: "What does Math.max(1, 5, 3) return?",
    options: ["1", "3", "5", "undefined"],
    answer: 2,
    explanation: "Math.max returns the largest value.",
  },
  {
    question: "Which event runs when a page finishes loading?",
    options: ["onopen", "onready", "onload", "onstart"],
    answer: 2,
    explanation: "onload fires when the page is loaded.",
  },
  {
    question: "Which keyword stops a switch case from falling through?",
    options: ["stop", "exit", "break", "return"],
    answer: 2,
    explanation: "break exits the switch case.",
  },
  {
    question: "What does localStorage store data as?",
    options: ["Objects", "Numbers", "Strings", "Booleans"],
    answer: 2,
    explanation: "localStorage stores values as strings.",
  },
  {
    question: "Which method clears all localStorage data?",
    options: ["remove()", "delete()", "clear()", "reset()"],
    answer: 2,
    explanation: "clear() removes all stored data.",
  },
  {
    question: "What does setInterval() do?",
    options: [
      "Runs code once",
      "Runs code repeatedly",
      "Stops code execution",
      "Delays execution once",
    ],
    answer: 1,
    explanation: "setInterval executes repeatedly.",
  },
  {
    question: "Which method stops setInterval?",
    options: [
      "clearTimeout()",
      "stopInterval()",
      "clearInterval()",
      "endInterval()",
    ],
    answer: 2,
    explanation: "clearInterval stops an interval.",
  },
  {
    question: "What does querySelector() return?",
    options: [
      "All matching elements",
      "The first matching element",
      "An array",
      "A string",
    ],
    answer: 1,
    explanation: "querySelector returns the first match.",
  },
  {
    question: "Which method selects multiple DOM elements?",
    options: [
      "getElement()",
      "querySelector()",
      "querySelectorAll()",
      "selectAll()",
    ],
    answer: 2,
    explanation: "querySelectorAll returns multiple elements.",
  },
  {
    question: "What does addEventListener() do?",
    options: [
      "Creates an event",
      "Removes an event",
      "Attaches an event handler",
      "Triggers an event",
    ],
    answer: 2,
    explanation: "It attaches an event handler to an element.",
  },
  {
    question: "Which keyword refers to the current object?",
    options: ["self", "this", "object", "current"],
    answer: 1,
    explanation: "this refers to the current object.",
  },
  {
    question: "What does typeof undefined return?",
    options: ["null", "undefined", "object", "number"],
    answer: 1,
    explanation: "typeof undefined returns 'undefined'.",
  },
  {
    question: "Which operator is used for default values?",
    options: ["||", "&&", "??", "?:?"],
    answer: 2,
    explanation: "The nullish coalescing operator sets defaults.",
  },
  {
    question: "What does trim() do to a string?",
    options: [
      "Removes all spaces",
      "Removes leading and trailing spaces",
      "Replaces spaces",
      "Counts spaces",
    ],
    answer: 1,
    explanation: "trim removes whitespace at both ends.",
  },
  {
    question: "What does split() return?",
    options: ["A string", "An object", "An array", "A number"],
    answer: 2,
    explanation: "split divides a string into an array.",
  },
  {
    question: "Which method converts a number to a string?",
    options: [
      "String()",
      "toString()",
      "Both String() and toString()",
      "parseInt()",
    ],
    answer: 2,
    explanation: "Both methods convert numbers to strings.",
  },
];
