const QUESTIONS = [
  {
    question: "What color is the sky on a clear day?",
    options: ["Green", "Blue", "Red", "Purple"],
    answer: 1,
    explanation: "The sky looks blue when it is clear.",
  },
  {
    question: "How many legs does a dog have?",
    options: ["2", "3", "4", "5"],
    answer: 2,
    explanation: "Dogs have 4 legs.",
  },
  {
    question: "Which animal says 'meow'?",
    options: ["Dog", "Cat", "Cow", "Bird"],
    answer: 1,
    explanation: "Cats say 'meow'.",
  },
  {
    question: "What do bees make?",
    options: ["Milk", "Honey", "Bread", "Juice"],
    answer: 1,
    explanation: "Bees make honey.",
  },
  {
    question: "Which planet do we live on?",
    options: ["Mars", "Venus", "Earth", "Jupiter"],
    answer: 2,
    explanation: "We live on Earth.",
  },
  {
    question: "What is 2 + 2?",
    options: ["3", "4", "5", "6"],
    answer: 1,
    explanation: "2 + 2 equals 4.",
  },
  {
    question: "Which animal is known as the king of the jungle?",
    options: ["Elephant", "Tiger", "Lion", "Monkey"],
    answer: 2,
    explanation: "The lion is called the king of the jungle.",
  },
  {
    question: "What do we drink that comes from cows?",
    options: ["Juice", "Water", "Milk", "Tea"],
    answer: 2,
    explanation: "Milk comes from cows.",
  },
  {
    question: "Which shape has 3 sides?",
    options: ["Circle", "Square", "Triangle", "Rectangle"],
    answer: 2,
    explanation: "A triangle has 3 sides.",
  },
  {
    question: "What color are bananas?",
    options: ["Blue", "Yellow", "Red", "Black"],
    answer: 1,
    explanation: "Bananas are yellow when ripe.",
  },
  {
    question: "How many days are in a week?",
    options: ["5", "6", "7", "8"],
    answer: 2,
    explanation: "There are 7 days in a week.",
  },
  {
    question: "Which animal can fly?",
    options: ["Dog", "Cat", "Bird", "Fish"],
    answer: 2,
    explanation: "Birds can fly.",
  },
  {
    question: "What do we use to write?",
    options: ["Spoon", "Pencil", "Plate", "Cup"],
    answer: 1,
    explanation: "We use a pencil to write.",
  },
  {
    question: "Which fruit is red?",
    options: ["Apple", "Banana", "Orange", "Pear"],
    answer: 0,
    explanation: "Apples are often red.",
  },
  {
    question: "What sound does a cow make?",
    options: ["Bark", "Meow", "Moo", "Roar"],
    answer: 2,
    explanation: "Cows say 'moo'.",
  },
  {
    question: "Which is the fastest land animal?",
    options: ["Elephant", "Cheetah", "Dog", "Horse"],
    answer: 1,
    explanation: "The cheetah is the fastest land animal.",
  },
  {
    question: "What do we use to see?",
    options: ["Ears", "Nose", "Eyes", "Hands"],
    answer: 2,
    explanation: "We use our eyes to see.",
  },
  {
    question: "Which meal do we eat in the morning?",
    options: ["Lunch", "Dinner", "Breakfast", "Snack"],
    answer: 2,
    explanation: "Breakfast is eaten in the morning.",
  },
  {
    question: "What is the color of grass?",
    options: ["Blue", "Green", "Yellow", "Pink"],
    answer: 1,
    explanation: "Grass is green.",
  },
  {
    question: "Which animal lives in water?",
    options: ["Dog", "Fish", "Cat", "Lion"],
    answer: 1,
    explanation: "Fish live in water.",
  },
  {
    question: "How many fingers do you have on one hand?",
    options: ["3", "4", "5", "6"],
    answer: 2,
    explanation: "You have 5 fingers on one hand.",
  },
  {
    question: "What do we use to tell time?",
    options: ["Book", "Clock", "Chair", "Bag"],
    answer: 1,
    explanation: "A clock tells time.",
  },
  {
    question: "Which season is very cold?",
    options: ["Summer", "Winter", "Spring", "Autumn"],
    answer: 1,
    explanation: "Winter is the cold season.",
  },
  {
    question: "Which animal is very big and has a trunk?",
    options: ["Dog", "Elephant", "Cat", "Goat"],
    answer: 1,
    explanation: "Elephants have trunks.",
  },
  {
    question: "What do plants need to grow?",
    options: ["Sand", "Water", "Plastic", "Metal"],
    answer: 1,
    explanation: "Plants need water to grow.",
  },

  {
    question: "Which animal lays eggs?",
    options: ["Dog", "Cat", "Chicken", "Goat"],
    answer: 2,
    explanation: "Chickens lay eggs.",
  },
  {
    question: "What do you call a baby dog?",
    options: ["Kitten", "Puppy", "Cub", "Calf"],
    answer: 1,
    explanation: "A baby dog is called a puppy.",
  },
  {
    question: "Which of these can you NOT eat?",
    options: ["Apple", "Bread", "Stone", "Rice"],
    answer: 2,
    explanation: "A stone is not food.",
  },
  {
    question: "What comes after the number 9?",
    options: ["8", "10", "11", "12"],
    answer: 1,
    explanation: "10 comes after 9.",
  },
  {
    question: "Which of these animals is the tallest?",
    options: ["Dog", "Cat", "Giraffe", "Goat"],
    answer: 2,
    explanation: "The giraffe is the tallest animal.",
  },
  {
    question: "What do we use to brush our teeth?",
    options: ["Comb", "Toothbrush", "Spoon", "Pen"],
    answer: 1,
    explanation: "We use a toothbrush to brush our teeth.",
  },
  {
    question: "Which one is a vehicle?",
    options: ["Chair", "Car", "Shoe", "Plate"],
    answer: 1,
    explanation: "A car is a vehicle used for transportation.",
  },
  {
    question: "Which part of the body helps you hear?",
    options: ["Eyes", "Nose", "Ears", "Hands"],
    answer: 2,
    explanation: "We use our ears to hear.",
  },
  {
    question: "Which is heavier?",
    options: ["Feather", "Stone", "Leaf", "Paper"],
    answer: 1,
    explanation: "A stone is heavier than the others.",
  },
  {
    question: "What do you wear on your feet?",
    options: ["Hat", "Gloves", "Shoes", "Shirt"],
    answer: 2,
    explanation: "Shoes are worn on the feet.",
  },
  {
    question: "Which of these is a wild animal?",
    options: ["Dog", "Cat", "Lion", "Cow"],
    answer: 2,
    explanation: "Lions are wild animals.",
  },
  {
    question: "What do plants give us that we breathe?",
    options: ["Water", "Oxygen", "Milk", "Juice"],
    answer: 1,
    explanation: "Plants give us oxygen to breathe.",
  },
  {
    question: "Which is the opposite of 'hot'?",
    options: ["Warm", "Cold", "Dry", "Big"],
    answer: 1,
    explanation: "Cold is the opposite of hot.",
  },
  {
    question: "Which shape is round?",
    options: ["Square", "Triangle", "Circle", "Rectangle"],
    answer: 2,
    explanation: "A circle is round.",
  },
  {
    question: "What do you call water when it freezes?",
    options: ["Steam", "Ice", "Rain", "Snow"],
    answer: 1,
    explanation: "Frozen water is called ice.",
  },
  {
    question: "Which animal can swim?",
    options: ["Lion", "Fish", "Goat", "Dog"],
    answer: 1,
    explanation: "Fish live and swim in water.",
  },
  {
    question: "What do we use to cut paper?",
    options: ["Spoon", "Scissors", "Plate", "Cup"],
    answer: 1,
    explanation: "Scissors are used to cut paper.",
  },
  {
    question: "Which is a type of weather?",
    options: ["Table", "Rain", "Shoe", "Book"],
    answer: 1,
    explanation: "Rain is a type of weather.",
  },
  {
    question: "What do you call a place where you learn?",
    options: ["Market", "School", "Farm", "Shop"],
    answer: 1,
    explanation: "A school is where you learn.",
  },
  {
    question: "Which of these is used to eat food?",
    options: ["Fork", "Broom", "Pen", "Book"],
    answer: 0,
    explanation: "A fork is used to eat food.",
  },
  {
    question: "Which animal has stripes?",
    options: ["Elephant", "Zebra", "Goat", "Cow"],
    answer: 1,
    explanation: "Zebras have black and white stripes.",
  },
  {
    question: "What do you use to carry your books to school?",
    options: ["Plate", "Bag", "Cup", "Shoe"],
    answer: 1,
    explanation: "A bag is used to carry books.",
  },
  {
    question: "Which is the first day of the week?",
    options: ["Monday", "Sunday", "Friday", "Wednesday"],
    answer: 1,
    explanation: "Sunday is often considered the first day of the week.",
  },
  {
    question: "Which of these can shine at night?",
    options: ["Sun", "Moon", "Cloud", "Tree"],
    answer: 1,
    explanation: "The moon shines at night.",
  },
  {
    question: "What do you call the home of a bird?",
    options: ["Cave", "Nest", "Den", "House"],
    answer: 1,
    explanation: "Birds live in nests.",
  },
];
