const QUESTIONS = [
  {
    question: "What color is the sky on a clear day?",
    image: "☀️",
    options: ["Green", "Blue", "Red", "Purple"],
    answer: 1,
    explanation: "The sky looks blue when it is clear.",
  },
  {
    question: "How many legs does a dog have?",
    image: "🐾",
    options: ["2", "3", "4", "5"],
    answer: 2,
    explanation: "Dogs have 4 legs.",
  },
  {
    question: "Which animal says 'meow'?",
    image: "🔊",
    options: ["Dog", "Cat", "Cow", "Bird"],
    answer: 1,
    explanation: "Cats say 'meow'.",
  },
  {
    question: "What do bees make?",
    image: "🌼",
    options: ["Milk", "Honey", "Bread", "Juice"],
    answer: 1,
    explanation: "Bees make honey.",
  },
  {
    question: "Which planet do we live on?",
    image: "🌍",
    options: ["Mars", "Venus", "Earth", "Jupiter"],
    answer: 2,
    explanation: "We live on Earth.",
  },
  {
    question: "What is 2 + 2?",
    image: "➕",
    options: ["3", "4", "5", "6"],
    answer: 1,
    explanation: "2 + 2 equals 4.",
  },
  {
    question: "Which animal is known as the king of the jungle?",
    image: "👑",
    options: ["Elephant", "Tiger", "Lion", "Monkey"],
    answer: 2,
    explanation: "The lion is called the king of the jungle.",
  },
  {
    question: "What do we drink that comes from cows?",
    image: "🥛",
    options: ["Juice", "Water", "Milk", "Tea"],
    answer: 2,
    explanation: "Milk comes from cows.",
  },
  {
    question: "Which shape has 3 sides?",
    image: "🔺",
    options: ["Circle", "Square", "Triangle", "Rectangle"],
    answer: 2,
    explanation: "A triangle has 3 sides.",
  },
  {
    question: "What color are bananas?",
    image: "🍌",
    options: ["Blue", "Yellow", "Red", "Black"],
    answer: 1,
    explanation: "Bananas are yellow when ripe.",
  },
  {
    question: "How many days are in a week?",
    image: "📅",
    options: ["5", "6", "7", "8"],
    answer: 2,
    explanation: "There are 7 days in a week.",
  },
  {
    question: "Which animal can fly?",
    image: "🌬️",
    options: ["Dog", "Cat", "Bird", "Fish"],
    answer: 2,
    explanation: "Birds can fly.",
  },
  {
    question: "What do we use to write?",
    image: "✍️",
    options: ["Spoon", "Pencil", "Plate", "Cup"],
    answer: 1,
    explanation: "We use a pencil to write.",
  },
  {
    question: "Which fruit is red?",
    image: "🎨",
    options: ["Apple", "Banana", "Orange", "Pear"],
    answer: 0,
    explanation: "Apples are often red.",
  },
  {
    question: "What sound does a cow make?",
    image: "🔉",
    options: ["Bark", "Meow", "Moo", "Roar"],
    answer: 2,
    explanation: "Cows say 'moo'.",
  },
  {
    question: "Which is the fastest land animal?",
    image: "⚡",
    options: ["Elephant", "Cheetah", "Dog", "Horse"],
    answer: 1,
    explanation: "The cheetah is the fastest land animal.",
  },
  {
    question: "What do we use to see?",
    image: "👀",
    options: ["Ears", "Nose", "Eyes", "Hands"],
    answer: 2,
    explanation: "We use our eyes to see.",
  },
  {
    question: "Which meal do we eat in the morning?",
    image: "🌅",
    options: ["Lunch", "Dinner", "Breakfast", "Snack"],
    answer: 2,
    explanation: "Breakfast is eaten in the morning.",
  },
  {
    question: "What is the color of grass?",
    image: "🌱",
    options: ["Blue", "Green", "Yellow", "Pink"],
    answer: 1,
    explanation: "Grass is green.",
  },
  {
    question: "Which animal lives in water?",
    image: "🌊",
    options: ["Dog", "Fish", "Cat", "Lion"],
    answer: 1,
    explanation: "Fish live in water.",
  },
  {
    question: "How many fingers do you have on one hand?",
    image: "✋",
    options: ["3", "4", "5", "6"],
    answer: 2,
    explanation: "You have 5 fingers on one hand.",
  },
  {
    question: "What do we use to tell time?",
    image: "⏳",
    options: ["Book", "Clock", "Chair", "Bag"],
    answer: 1,
    explanation: "A clock tells time.",
  },
  {
    question: "Which season is very cold?",
    image: "❄️",
    options: ["Summer", "Winter", "Spring", "Autumn"],
    answer: 1,
    explanation: "Winter is the cold season.",
  },
  {
    question: "Which animal is very big and has a trunk?",
    image: "🌿",
    options: ["Dog", "Elephant", "Cat", "Goat"],
    answer: 1,
    explanation: "Elephants have trunks.",
  },
  {
    question: "What do plants need to grow?",
    image: "🌞",
    options: ["Sand", "Water", "Plastic", "Metal"],
    answer: 1,
    explanation: "Plants need water to grow.",
  },

  {
    question: "Which animal lays eggs?",
    image: "🥚",
    options: ["Dog", "Cat", "Chicken", "Goat"],
    answer: 2,
    explanation: "Chickens lay eggs.",
  },
  {
    question: "What do you call a baby dog?",
    image: "👶",
    options: ["Kitten", "Puppy", "Cub", "Calf"],
    answer: 1,
    explanation: "A baby dog is called a puppy.",
  },
  {
    question: "Which of these can you NOT eat?",
    image: "🍽️",
    options: ["Apple", "Bread", "Stone", "Rice"],
    answer: 2,
    explanation: "A stone is not food.",
  },
  {
    question: "What comes after the number 9?",
    image: "🔢",
    options: ["8", "10", "11", "12"],
    answer: 1,
    explanation: "10 comes after 9.",
  },
  {
    question: "Which of these animals is the tallest?",
    image: "📏",
    options: ["Dog", "Cat", "Giraffe", "Goat"],
    answer: 2,
    explanation: "The giraffe is the tallest animal.",
  },
  {
    question: "What do we use to brush our teeth?",
    image: "🪥",
    options: ["Comb", "Toothbrush", "Spoon", "Pen"],
    answer: 1,
    explanation: "We use a toothbrush to brush our teeth.",
  },
  {
    question: "Which one is a vehicle?",
    image: "🛣️",
    options: ["Chair", "Car", "Shoe", "Plate"],
    answer: 1,
    explanation: "A car is a vehicle used for transportation.",
  },
  {
    question: "Which part of the body helps you hear?",
    image: "👂",
    options: ["Eyes", "Nose", "Ears", "Hands"],
    answer: 2,
    explanation: "We use our ears to hear.",
  },
  {
    question: "Which is heavier?",
    image: "⚖️",
    options: ["Feather", "Stone", "Leaf", "Paper"],
    answer: 1,
    explanation: "A stone is heavier than the others.",
  },
  {
    question: "What do you wear on your feet?",
    image: "👣",
    options: ["Hat", "Gloves", "Shoes", "Shirt"],
    answer: 2,
    explanation: "Shoes are worn on the feet.",
  },
  {
    question: "Which of these is a wild animal?",
    image: "🌳",
    options: ["Dog", "Cat", "Lion", "Cow"],
    answer: 2,
    explanation: "Lions are wild animals.",
  },
  {
    question: "What do plants give us that we breathe?",
    image: "🌿",
    options: ["Water", "Oxygen", "Milk", "Juice"],
    answer: 1,
    explanation: "Plants give us oxygen to breathe.",
  },
  {
    question: "Which is the opposite of 'hot'?",
    image: "🌡️",
    options: ["Warm", "Cold", "Dry", "Big"],
    answer: 1,
    explanation: "Cold is the opposite of hot.",
  },
  {
    question: "Which shape is round?",
    image: "🔵",
    options: ["Square", "Triangle", "Circle", "Rectangle"],
    answer: 2,
    explanation: "A circle is round.",
  },
  {
    question: "What do you call water when it freezes?",
    image: "❄️",
    options: ["Steam", "Ice", "Rain", "Snow"],
    answer: 1,
    explanation: "Frozen water is called ice.",
  },
  {
    question: "Which animal can swim?",
    image: "🌊",
    options: ["Lion", "Fish", "Goat", "Dog"],
    answer: 1,
    explanation: "Fish live and swim in water.",
  },
  {
    question: "What do we use to cut paper?",
    image: "✂️",
    options: ["Spoon", "Scissors", "Plate", "Cup"],
    answer: 1,
    explanation: "Scissors are used to cut paper.",
  },
  {
    question: "Which is a type of weather?",
    image: "☁️",
    options: ["Table", "Rain", "Shoe", "Book"],
    answer: 1,
    explanation: "Rain is a type of weather.",
  },
  {
    question: "What do you call a place where you learn?",
    image: "📚",
    options: ["Market", "School", "Farm", "Shop"],
    answer: 1,
    explanation: "A school is where you learn.",
  },
  {
    question: "Which of these is used to eat food?",
    image: "🍴",
    options: ["Fork", "Broom", "Pen", "Book"],
    answer: 0,
    explanation: "A fork is used to eat food.",
  },
  {
    question: "Which animal has stripes?",
    image: "🎨",
    options: ["Elephant", "Zebra", "Goat", "Cow"],
    answer: 1,
    explanation: "Zebras have black and white stripes.",
  },
  {
    question: "What do you use to carry your books to school?",
    image: "🎒",
    options: ["Plate", "Bag", "Cup", "Shoe"],
    answer: 1,
    explanation: "A bag is used to carry books.",
  },
  {
    question: "Which is the first day of the week?",
    image: "📅",
    options: ["Monday", "Sunday", "Friday", "Wednesday"],
    answer: 1,
    explanation: "Sunday is often considered the first day of the week.",
  },
  {
    question: "Which of these can shine at night?",
    image: "🌙",
    options: ["Sun", "Moon", "Cloud", "Tree"],
    answer: 1,
    explanation: "The moon shines at night.",
  },
  {
    question: "What do you call the home of a bird?",
    image: "🌳",
    options: ["Cave", "Nest", "Den", "House"],
    answer: 1,
    explanation: "Birds live in nests.",
  },

  {
    question: "Which one of these can fly without wings?",
    image: "🌬️",
    options: ["Dog", "Kite", "Fish", "Goat"],
    answer: 1,
    explanation: "A kite can fly in the air using wind.",
  },
  {
    question: "What has hands but cannot clap?",
    image: "🤲",
    options: ["Baby", "Clock", "Monkey", "Robot"],
    answer: 1,
    explanation: "A clock has hands but cannot clap.",
  },
  {
    question: "Which one is NOT alive?",
    image: "🏠",
    options: ["Tree", "Dog", "Chair", "Bird"],
    answer: 2,
    explanation: "A chair is not alive.",
  },
  {
    question: "What gets wetter the more it dries?",
    image: "💧",
    options: ["Paper", "Towel", "Sponge", "Cloth"],
    answer: 1,
    explanation: "A towel gets wetter as it dries things.",
  },
  {
    question: "Which animal can jump the highest?",
    image: "⬆️",
    options: ["Elephant", "Kangaroo", "Dog", "Cow"],
    answer: 1,
    explanation: "Kangaroos are great jumpers.",
  },
  {
    question: "Which one is the odd one out?",
    image: "🍽️",
    options: ["Apple", "Banana", "Carrot", "Orange"],
    answer: 2,
    explanation: "Carrot is a vegetable, others are fruits.",
  },
  {
    question: "What do you use to see stars at night?",
    image: "🌙",
    options: ["Microscope", "Telescope", "Glasses", "Camera"],
    answer: 1,
    explanation: "A telescope helps you see stars.",
  },
  {
    question: "Which is faster?",
    image: "🏁",
    options: ["Tortoise", "Rabbit", "Snail", "Duck"],
    answer: 1,
    explanation: "Rabbits are faster than tortoises.",
  },
  {
    question: "Which one melts in the sun?",
    image: "☀️",
    options: ["Stone", "Ice", "Wood", "Metal"],
    answer: 1,
    explanation: "Ice melts when heated.",
  },
  {
    question: "What has a face and two hands but no arms or legs?",
    image: "🙂",
    options: ["Doll", "Clock", "Man", "Toy"],
    answer: 1,
    explanation: "A clock has a face and hands.",
  },
  {
    question: "Which one can you catch but not throw?",
    image: "🤒",
    options: ["Ball", "Cold", "Stick", "Toy"],
    answer: 1,
    explanation: "You can catch a cold.",
  },
  {
    question: "Which of these is the lightest?",
    image: "🎈",
    options: ["Stone", "Feather", "Book", "Bottle"],
    answer: 1,
    explanation: "A feather is very light.",
  },
  {
    question: "What goes up but never comes down?",
    image: "📈",
    options: ["Ball", "Age", "Bird", "Smoke"],
    answer: 1,
    explanation: "Your age always increases.",
  },
  {
    question: "Which one has a long neck?",
    image: "📏",
    options: ["Dog", "Giraffe", "Cat", "Pig"],
    answer: 1,
    explanation: "Giraffes have long necks.",
  },
  {
    question: "Which is NOT a fruit?",
    image: "🧺",
    options: ["Tomato", "Potato", "Apple", "Mango"],
    answer: 1,
    explanation: "Potato is a vegetable.",
  },
  {
    question: "What do you wear when it rains?",
    image: "☁️",
    options: ["Sunglasses", "Raincoat", "Slippers", "Cap"],
    answer: 1,
    explanation: "A raincoat keeps you dry.",
  },
  {
    question: "Which animal says 'oink'?",
    image: "🎵",
    options: ["Cow", "Pig", "Goat", "Dog"],
    answer: 1,
    explanation: "Pigs say 'oink'.",
  },
  {
    question: "Which one is used to unlock a door?",
    image: "🚪",
    options: ["Knife", "Key", "Stick", "Pen"],
    answer: 1,
    explanation: "A key opens a lock.",
  },
  {
    question: "What has one eye but cannot see?",
    image: "🧵",
    options: ["Needle", "Cyclops", "Fish", "Camera"],
    answer: 0,
    explanation: "A needle has an eye for thread.",
  },
  {
    question: "Which is bigger?",
    image: "⚖️",
    options: ["Moon", "Earth", "Star", "Ball"],
    answer: 1,
    explanation: "Earth is bigger than the moon.",
  },
  {
    question: "Which one is cold?",
    image: "❄️",
    options: ["Soup", "Ice cream", "Tea", "Rice"],
    answer: 1,
    explanation: "Ice cream is cold.",
  },
  {
    question: "Which one can you hear but not see?",
    image: "👂",
    options: ["Music", "Ball", "Book", "Car"],
    answer: 0,
    explanation: "You hear music but cannot see it.",
  },
  {
    question: "Which animal is known for black and white color?",
    image: "🎨",
    options: ["Tiger", "Zebra", "Panda", "Dog"],
    answer: 2,
    explanation: "Pandas are black and white.",
  },
  {
    question: "What do you use to tell directions?",
    image: "🗺️",
    options: ["Clock", "Compass", "Phone", "Book"],
    answer: 1,
    explanation: "A compass shows direction.",
  },
  {
    question: "Which one is NOT a shape?",
    image: "🔷",
    options: ["Circle", "Triangle", "Ball", "Square"],
    answer: 2,
    explanation: "A ball is an object, not a flat shape.",
  },

  {
    image: "🐾",
    question: "Which animal could these footprints belong to?",
    options: ["Dog", "Fish", "Bird"],
    answer: 0,
    explanation: "Dogs have paw prints like this.",
  },
  {
    image: "🥚",
    question: "What comes out of this?",
    options: ["Baby chicken", "Milk", "Juice"],
    answer: 0,
    explanation: "Eggs hatch into baby chickens.",
  },
  {
    image: "🌙",
    question: "When do you usually see this?",
    options: ["Daytime", "Nighttime"],
    answer: 1,
    explanation: "The moon is mostly seen at night.",
  },
  {
    image: "❄️",
    question: "Is this hot or cold?",
    options: ["Hot", "Cold"],
    answer: 1,
    explanation: "Snow and ice are cold.",
  },
  {
    image: "🛞",
    question: "What uses this to move?",
    options: ["Car", "Tree", "House"],
    answer: 0,
    explanation: "Cars use wheels to move.",
  },
  {
    image: "🦷",
    question: "What do you use to clean this?",
    options: ["Toothbrush", "Spoon", "Pen"],
    answer: 0,
    explanation: "You clean teeth with a toothbrush.",
  },
  {
    image: "🌧️",
    question: "What should you take when you see this?",
    options: ["Umbrella", "Sunglasses", "Fan"],
    answer: 0,
    explanation: "Rain means you may need an umbrella.",
  },
  {
    image: "🔥",
    question: "True or False: You should touch this.",
    options: ["True", "False"],
    answer: 1,
    explanation: "Fire is hot and dangerous to touch.",
  },
  {
    image: "📚",
    question: "Where do you usually use these?",
    options: ["School", "Bathroom", "Kitchen"],
    answer: 0,
    explanation: "Books are mostly used in school.",
  },
  {
    image: "🍌",
    question: "What color is this usually?",
    options: ["Blue", "Yellow", "Purple"],
    answer: 1,
    explanation: "Bananas are usually yellow.",
  },
  {
    image: "🐟",
    question: "Where does this live?",
    options: ["Water", "Sky", "Tree"],
    answer: 0,
    explanation: "Fish live in water.",
  },
  {
    image: "👀",
    question: "What do you use these for?",
    options: ["Hearing", "Seeing", "Smelling"],
    answer: 1,
    explanation: "Eyes are used for seeing.",
  },
  {
    image: "🍴",
    question: "What do you use this for?",
    options: ["Eating", "Sleeping", "Running"],
    answer: 0,
    explanation: "Forks are used for eating.",
  },
  {
    image: "🚪",
    question: "What do you need to open this?",
    options: ["Key", "Plate", "Shoe"],
    answer: 0,
    explanation: "Doors are opened with keys.",
  },
  {
    image: "🌳",
    question: "What grows on this?",
    options: ["Fish", "Fruits", "Shoes"],
    answer: 1,
    explanation: "Trees grow fruits.",
  },
  {
    image: "🧊",
    question: "What happens to this in the sun?",
    options: ["Melts", "Grows", "Flies"],
    answer: 0,
    explanation: "Ice melts in heat.",
  },
  {
    image: "✈️",
    question: "Where does this travel?",
    options: ["Road", "Sky", "Water"],
    answer: 1,
    explanation: "Airplanes fly in the sky.",
  },
  {
    image: "🧒",
    question: "True or False: This is an adult.",
    options: ["True", "False"],
    answer: 1,
    explanation: "This represents a child.",
  },
  {
    image: "🍞",
    question: "Which meal can include this?",
    options: ["Breakfast", "Swimming", "Sleeping"],
    answer: 0,
    explanation: "Bread is often eaten at breakfast.",
  },
  {
    image: "🐄",
    question: "What does this animal give us?",
    options: ["Milk", "Juice", "Sand"],
    answer: 0,
    explanation: "Cows give milk.",
  },
  {
    image: "⏰",
    question: "What does this help you know?",
    options: ["Time", "Color", "Taste"],
    answer: 0,
    explanation: "Clocks tell time.",
  },
  {
    image: "🌞",
    question: "When do you see this?",
    options: ["Day", "Night"],
    answer: 0,
    explanation: "The sun appears during the day.",
  },
  {
    image: "👟",
    question: "Where do you wear this?",
    options: ["Head", "Feet", "Hands"],
    answer: 1,
    explanation: "Shoes are worn on the feet.",
  },
  {
    image: "🧭",
    question: "What does this help you find?",
    options: ["Direction", "Food", "Music"],
    answer: 0,
    explanation: "A compass shows direction.",
  },
  {
    image: "🎈",
    question: "Does this go up or down?",
    options: ["Up", "Down"],
    answer: 0,
    explanation: "Balloons float up.",
  },
];
