const QUESTIONS = [
  {
    question: "Which function is used to display output in Python?",
    options: ["echo()", "print()", "write()", "display()"],
    answer: 1,
    explanation: "print() outputs text to the console.",
  },
  {
    question: "Which symbol is used to assign a value to a variable?",
    options: ["==", "=", ":=", "=>"],
    answer: 1,
    explanation: "= assigns a value to a variable.",
  },
  {
    question: "What is the correct file extension for a Python file?",
    options: [".pt", ".python", ".py", ".pyt"],
    answer: 2,
    explanation: "Python files use the .py extension.",
  },
  {
    question: "Which of these is a valid variable name?",
    options: ["2name", "user-name", "user_name", "user name"],
    answer: 2,
    explanation:
      "Variable names can include underscores but not spaces or hyphens.",
  },
  {
    question: "What data type is the value 10?",
    options: ["str", "float", "int", "bool"],
    answer: 2,
    explanation: "10 is an integer.",
  },
  {
    question: "What data type is the value 10.5?",
    options: ["int", "float", "str", "bool"],
    answer: 1,
    explanation: "10.5 is a floating-point number.",
  },
  {
    question: "Which keyword is used to define a function?",
    options: ["function", "define", "def", "func"],
    answer: 2,
    explanation: "Functions are defined using def.",
  },
  {
    question: 'What will len("Python") return?',
    options: ["5", "6", "7", "Error"],
    answer: 1,
    explanation: 'The string "Python" has 6 characters.',
  },
  {
    question: "Which operator is used for equality comparison?",
    options: ["=", "==", "!=", "<="],
    answer: 1,
    explanation: "== checks if two values are equal.",
  },
  {
    question: "How do you start a comment in Python?",
    options: ["//", "#", "/*", "<!--"],
    answer: 1,
    explanation: "Python comments start with #.",
  },
  {
    question: "Which keyword is used to make a decision in Python?",
    options: ["for", "while", "if", "def"],
    answer: 2,
    explanation: "if is used for conditional decisions.",
  },
  {
    question: "What will type(True) return?",
    options: ["bool", "int", "str", "None"],
    answer: 0,
    explanation: "True is a boolean value.",
  },
  {
    question: "Which data type is used to store multiple ordered items?",
    options: ["dict", "set", "tuple", "list"],
    answer: 3,
    explanation: "Lists store ordered collections of items.",
  },
  {
    question: "How do you access the first element of a list named nums?",
    options: ["nums(0)", "nums[1]", "nums[0]", "nums.first()"],
    answer: 2,
    explanation: "Python lists are zero-indexed.",
  },
  {
    question: "Which keyword is used to loop over a sequence?",
    options: ["loop", "repeat", "for", "iterate"],
    answer: 2,
    explanation: "for is used to iterate over sequences.",
  },
  {
    question: "What does the range(3) function produce?",
    options: ["0, 1, 2", "1, 2, 3", "0, 1, 2, 3", "3"],
    answer: 0,
    explanation: "range(3) generates numbers from 0 to 2.",
  },
  {
    question: "Which keyword is used to stop a loop early?",
    options: ["stop", "exit", "break", "end"],
    answer: 2,
    explanation: "break exits a loop immediately.",
  },
  {
    question: "Which keyword skips the current loop iteration?",
    options: ["skip", "pass", "continue", "next"],
    answer: 2,
    explanation: "continue skips to the next iteration.",
  },
  {
    question: "What is the result of 3 + 2 * 2?",
    options: ["10", "7", "8", "9"],
    answer: 1,
    explanation: "Multiplication happens before addition.",
  },
  {
    question: "Which function converts input into a string?",
    options: ["str()", "int()", "input()", "print()"],
    answer: 0,
    explanation: "str() converts values to strings.",
  },
  {
    question: "What does input() return?",
    options: ["int", "float", "str", "bool"],
    answer: 2,
    explanation: "input() always returns a string.",
  },
  {
    question: "Which keyword is used to handle errors?",
    options: ["catch", "error", "try", "handle"],
    answer: 2,
    explanation: "try is used to wrap code that may raise errors.",
  },
  {
    question: "Which block runs if an error occurs?",
    options: ["finally", "else", "except", "error"],
    answer: 2,
    explanation: "except handles exceptions.",
  },
  {
    question: "What does the append() method do to a list?",
    options: [
      "Removes an item",
      "Adds an item to the end",
      "Sorts the list",
      "Replaces the list",
    ],
    answer: 1,
    explanation: "append() adds an item to the end of a list.",
  },
  {
    question: "Which method removes the last item from a list?",
    options: ["remove()", "delete()", "pop()", "clear()"],
    answer: 2,
    explanation: "pop() removes and returns the last item.",
  },
  {
    question: "Which data type stores key-value pairs?",
    options: ["list", "tuple", "dict", "set"],
    answer: 2,
    explanation: "Dictionaries store data as key-value pairs.",
  },
  {
    question:
      "How do you get a value from a dictionary named data using key 'age'?",
    options: ["data.age", "data['age']", "data(age)", "data.get.age"],
    answer: 1,
    explanation: "Dictionary values are accessed using square brackets.",
  },
  {
    question: "Which keyword is used to define a class?",
    options: ["object", "define", "class", "struct"],
    answer: 2,
    explanation: "Classes are defined using the class keyword.",
  },
  {
    question:
      "What is the default return value of a function with no return statement?",
    options: ["0", "False", "None", "Error"],
    answer: 2,
    explanation: "Functions return None by default.",
  },
  {
    question: "Which keyword is used to import a module?",
    options: ["include", "using", "import", "require"],
    answer: 2,
    explanation: "Modules are imported using import.",
  },
  {
    question: "What does bool(0) return?",
    options: ["True", "False", "0", "None"],
    answer: 1,
    explanation: "0 is considered False in boolean context.",
  },
  {
    question: "Which operator checks if a value is not equal?",
    options: ["==", "!=", "<>", "="],
    answer: 1,
    explanation: "!= means not equal.",
  },
  {
    question: "Which method converts a string to lowercase?",
    options: ["lower()", "down()", "small()", "casefold()"],
    answer: 0,
    explanation: "lower() converts text to lowercase.",
  },
  {
    question: 'What will "Hello"[1] return?',
    options: ["H", "e", "l", "o"],
    answer: 1,
    explanation: "Index 1 refers to the second character.",
  },
  {
    question:
      "Which keyword is used to create a loop that runs while a condition is true?",
    options: ["for", "loop", "repeat", "while"],
    answer: 3,
    explanation: "while loops run based on a condition.",
  },
  {
    question: "What does the pass keyword do?",
    options: [
      "Stops execution",
      "Skips iteration",
      "Does nothing",
      "Ends a function",
    ],
    answer: 2,
    explanation: "pass is a placeholder that does nothing.",
  },
  {
    question: "Which function returns the largest value?",
    options: ["top()", "big()", "max()", "largest()"],
    answer: 2,
    explanation: "max() returns the highest value.",
  },
  {
    question: "Which function returns the smallest value?",
    options: ["min()", "small()", "lowest()", "short()"],
    answer: 0,
    explanation: "min() returns the lowest value.",
  },
  {
    question: "What does the clear() method do to a list?",
    options: [
      "Deletes the list",
      "Empties the list",
      "Sorts the list",
      "Copies the list",
    ],
    answer: 1,
    explanation: "clear() removes all items from the list.",
  },
  {
    question: "Which keyword is used to define a constant in Python?",
    options: ["const", "final", "static", "None of the above"],
    answer: 3,
    explanation: "Python has no built-in constant keyword.",
  },
  {
    question: "Which symbol is used for exponentiation?",
    options: ["^", "**", "*", "//"],
    answer: 1,
    explanation: "** is the exponent operator.",
  },
  {
    question: "What does the // operator do?",
    options: [
      "Normal division",
      "Remainder division",
      "Floor division",
      "Exponentiation",
    ],
    answer: 2,
    explanation: "// performs floor division.",
  },
  {
    question: "Which function converts a string to an integer?",
    options: ["str()", "float()", "int()", "bool()"],
    answer: 2,
    explanation: "int() converts compatible strings to integers.",
  },
  {
    question: "Which value represents 'no value' in Python?",
    options: ["0", "False", "None", "Empty"],
    answer: 2,
    explanation: "None represents the absence of a value.",
  },
  {
    question: "Which keyword checks multiple conditions after an if?",
    options: ["else if", "elseif", "elif", "else"],
    answer: 2,
    explanation: "elif checks additional conditions.",
  },
  {
    question: "What will list(range(2, 5)) return?",
    options: ["[2, 3, 4]", "[2, 3, 4, 5]", "[3, 4, 5]", "[2, 4]"],
    answer: 0,
    explanation: "range excludes the stop value.",
  },
  {
    question: "Which method checks if a string starts with a specific value?",
    options: ["starts()", "startswith()", "begin()", "has()"],
    answer: 1,
    explanation: "startswith() checks the beginning of a string.",
  },
  {
    question: "Which keyword is used to create an empty class in Python?",
    options: ["empty", "class", "def", "pass"],
    answer: 3,
    explanation:
      "pass is used as a placeholder for an empty class or function.",
  },
  {
    question: "What is the output of type([])?",
    options: ["list", "tuple", "dict", "set"],
    answer: 0,
    explanation: "[] creates an empty list.",
  },
  {
    question: "Which method adds multiple elements to the end of a list?",
    options: ["extend()", "append()", "insert()", "add()"],
    answer: 0,
    explanation: "extend() adds all elements from another list.",
  },
  {
    question: "How do you create a tuple with one element?",
    options: ["(1)", "(1,)", "tuple(1)", "[1]"],
    answer: 1,
    explanation: "A trailing comma is needed for a single-element tuple.",
  },
  {
    question: "Which data type is immutable?",
    options: ["list", "tuple", "dict", "set"],
    answer: 1,
    explanation: "Tuples cannot be modified after creation.",
  },
  {
    question: "Which keyword is used to check identity of objects?",
    options: ["is", "==", "equals", "identity"],
    answer: 0,
    explanation: "is checks if two variables refer to the same object.",
  },
  {
    question: "Which method removes an item by value from a list?",
    options: ["pop()", "remove()", "delete()", "discard()"],
    answer: 1,
    explanation:
      "remove() deletes the first occurrence of the specified value.",
  },
  {
    question: "Which of these is a set in Python?",
    options: ["{1, 2, 3}", "[1, 2, 3]", "(1, 2, 3)", "{'a':1}"],
    answer: 0,
    explanation: "Curly braces with comma-separated values create a set.",
  },
  {
    question: "What does the discard() method do in a set?",
    options: [
      "Removes an item and raises error if missing",
      "Removes an item if present",
      "Deletes the set",
      "Clears the set",
    ],
    answer: 1,
    explanation: "discard() removes an element without error if it is absent.",
  },
  {
    question: "Which method converts a string into a list of words?",
    options: ["split()", "join()", "slice()", "partition()"],
    answer: 0,
    explanation:
      "split() divides a string into a list based on whitespace or a separator.",
  },
  {
    question: "Which method joins a list of strings into a single string?",
    options: ["split()", "join()", "merge()", "concat()"],
    answer: 1,
    explanation: "join() concatenates elements of a list into a string.",
  },
  {
    question: "What does the strip() method do?",
    options: [
      "Removes all spaces",
      "Removes leading and trailing whitespace",
      "Removes all characters",
      "Converts to string",
    ],
    answer: 1,
    explanation: "strip() removes whitespace from both ends of a string.",
  },
  {
    question: "Which operator checks membership in a sequence?",
    options: ["in", "==", "is", "has"],
    answer: 0,
    explanation: "in checks if a value exists in a sequence.",
  },
  {
    question: "Which of these is used to create an empty dictionary?",
    options: ["{}", "[]", "()", "set()"],
    answer: 0,
    explanation: "{} creates an empty dictionary.",
  },
  {
    question: "What is the output of bool([])?",
    options: ["True", "False", "None", "Error"],
    answer: 1,
    explanation: "Empty lists are considered False.",
  },
  {
    question: "Which method returns a copy of a list?",
    options: ["copy()", "clone()", "duplicate()", "list()"],
    answer: 0,
    explanation: "copy() creates a shallow copy of the list.",
  },
  {
    question: "Which function returns the absolute value of a number?",
    options: ["abs()", "absolute()", "mod()", "value()"],
    answer: 0,
    explanation: "abs() returns the non-negative value of a number.",
  },
  {
    question: "Which function rounds a number to the nearest integer?",
    options: ["floor()", "ceil()", "round()", "truncate()"],
    answer: 2,
    explanation: "round() rounds to the nearest integer.",
  },
  {
    question: "What is the result of 7 % 3?",
    options: ["1", "2", "3", "0"],
    answer: 1,
    explanation: "% gives the remainder of division.",
  },
  {
    question: "Which function converts a value to a float?",
    options: ["int()", "float()", "str()", "decimal()"],
    answer: 1,
    explanation:
      "float() converts compatible values to a floating-point number.",
  },
  {
    question: "What is the result of bool('')?",
    options: ["True", "False", "None", "Error"],
    answer: 1,
    explanation: "Empty strings are considered False.",
  },
  {
    question: "Which function returns the sum of all elements in an iterable?",
    options: ["sum()", "add()", "total()", "combine()"],
    answer: 0,
    explanation: "sum() calculates the total of numeric elements.",
  },
  {
    question: "Which function returns the minimum value in an iterable?",
    options: ["min()", "smallest()", "lowest()", "minvalue()"],
    answer: 0,
    explanation: "min() returns the smallest element.",
  },
  {
    question: "Which function returns the maximum value in an iterable?",
    options: ["max()", "largest()", "high()", "top()"],
    answer: 0,
    explanation: "max() returns the largest element.",
  },
  {
    question: "What will the expression 2 ** 3 evaluate to?",
    options: ["5", "6", "8", "9"],
    answer: 2,
    explanation: "** is the exponent operator, so 2^3 = 8.",
  },
  {
    question: "Which keyword is used to execute code regardless of exceptions?",
    options: ["finally", "except", "else", "ensure"],
    answer: 0,
    explanation: "finally runs code no matter what happens in try/except.",
  },
  {
    question: "What does the pass statement do inside a function?",
    options: [
      "Exits the function",
      "Does nothing",
      "Returns None",
      "Raises error",
    ],
    answer: 1,
    explanation: "pass is a placeholder that does nothing.",
  },
  {
    question: "Which function returns the length of a list, string, or tuple?",
    options: ["length()", "count()", "len()", "size()"],
    answer: 2,
    explanation: "len() returns the number of elements.",
  },
  {
    question: "Which method sorts a list in place?",
    options: ["sort()", "sorted()", "order()", "arrange()"],
    answer: 0,
    explanation: "sort() modifies the list to be in order.",
  },
  {
    question:
      "Which function returns a sorted copy of a list without changing the original?",
    options: ["sort()", "sorted()", "order()", "arrange()"],
    answer: 1,
    explanation: "sorted() returns a new sorted list.",
  },
  {
    question: "Which keyword is used to define an anonymous function?",
    options: ["def", "lambda", "func", "anon"],
    answer: 1,
    explanation: "lambda creates small anonymous functions.",
  },
  {
    question: "What will 5 // 2 return?",
    options: ["2.5", "2", "3", "Error"],
    answer: 1,
    explanation: "// performs floor division.",
  },
  {
    question: "Which function returns an iterator over a sequence of numbers?",
    options: ["range()", "enumerate()", "list()", "iter()"],
    answer: 0,
    explanation: "range() generates numbers lazily for iteration.",
  },
  {
    question: "Which function enumerates items with their index?",
    options: ["range()", "enumerate()", "zip()", "index()"],
    answer: 1,
    explanation: "enumerate() adds an index to iterable items.",
  },
  {
    question: "Which function combines multiple iterables element-wise?",
    options: ["zip()", "combine()", "merge()", "concat()"],
    answer: 0,
    explanation: "zip() pairs elements from multiple iterables.",
  },
  {
    question: "Which method converts all characters in a string to uppercase?",
    options: ["upper()", "capitalize()", "title()", "big()"],
    answer: 0,
    explanation: "upper() converts all letters to uppercase.",
  },
  {
    question:
      "Which method returns the index of the first occurrence of a substring?",
    options: ["find()", "index()", "search()", "locate()"],
    answer: 0,
    explanation: "find() returns the position or -1 if not found.",
  },
  {
    question: "What is the output of list('abc')?",
    options: ["['abc']", "['a', 'b', 'c']", "['a','bc']", "['ab','c']"],
    answer: 1,
    explanation: "list() converts a string into a list of its characters.",
  },
  {
    question: "Which method removes all items from a dictionary?",
    options: ["delete()", "remove()", "clear()", "pop()"],
    answer: 2,
    explanation: "clear() empties the dictionary.",
  },
  {
    question: "Which keyword is used to handle exceptions?",
    options: ["try", "catch", "except", "error"],
    answer: 2,
    explanation: "except catches exceptions raised in try blocks.",
  },
  {
    question: "Which operator concatenates two strings?",
    options: ["+", "&", ".", "*"],
    answer: 0,
    explanation: "+ joins strings together.",
  },
  {
    question: "Which method removes leading whitespace from a string?",
    options: ["lstrip()", "rstrip()", "strip()", "trim()"],
    answer: 0,
    explanation: "lstrip() removes spaces from the left side.",
  },
  {
    question: "Which method removes trailing whitespace from a string?",
    options: ["lstrip()", "rstrip()", "strip()", "trim()"],
    answer: 1,
    explanation: "rstrip() removes spaces from the right side.",
  },
  {
    question:
      "Which function returns the character corresponding to an ASCII code?",
    options: ["ord()", "chr()", "ascii()", "code()"],
    answer: 1,
    explanation: "chr() returns the character for a given integer.",
  },
  {
    question: "Which function returns the ASCII code of a character?",
    options: ["ord()", "chr()", "ascii()", "code()"],
    answer: 0,
    explanation: "ord() returns the Unicode code of a character.",
  },
  {
    question: "Which method checks if all characters in a string are digits?",
    options: ["isdigit()", "isnumeric()", "isdecimal()", "all()"],
    answer: 0,
    explanation: "isdigit() returns True if all characters are digits.",
  },
  {
    question: "Which function returns a reversed iterator over a sequence?",
    options: ["reverse()", "reversed()", "invert()", "backwards()"],
    answer: 1,
    explanation: "reversed() returns an iterator in reverse order.",
  },
  {
    question: "Which operator repeats a sequence multiple times?",
    options: ["*", "+", "%", "**"],
    answer: 0,
    explanation: "* repeats sequences like strings or lists.",
  },
  {
    question: "Which method counts occurrences of a value in a list?",
    options: ["count()", "frequency()", "occurrences()", "find()"],
    answer: 0,
    explanation: "count() returns how many times a value appears.",
  },
  {
    question: "Which statement is used to exit a function and return a value?",
    options: ["stop", "exit", "return", "break"],
    answer: 2,
    explanation: "return exits the function and optionally provides a value.",
  },

  {
    question:
      'What will be printed? \nimport asyncio\n\nasync def main():\n    print("Hello Async")\n\nasyncio.run(main())',
    options: ["0. Nothing", "1. Hello Async", "2. Error", "3. None"],
    answer: 1,
    explanation:
      "asyncio.run() executes the coroutine, so 'Hello Async' prints.",
  },
  {
    question:
      'What happens here? \nasync def greet():\n    return "Hi"\n\ngreet()',
    options: [
      "0. Prints Hi",
      "1. Returns coroutine object",
      "2. Error",
      "3. Returns None",
    ],
    answer: 1,
    explanation:
      "Calling an async function without await returns a coroutine object.",
  },
  {
    question:
      'What will be printed?\nimport asyncio\n\nasync def main():\n    await asyncio.sleep(1)\n    print("Done")\n\nasyncio.run(main())',
    options: [
      "0. Done immediately",
      "1. Nothing",
      "2. Done after 1 second",
      "3. Error",
    ],
    answer: 2,
    explanation:
      "asyncio.sleep waits asynchronously for 1 second before printing.",
  },
  {
    question: "Which keyword makes a function asynchronous?",
    options: ["0. await", "1. async", "2. yield", "3. lambda"],
    answer: 1,
    explanation:
      "The 'async' keyword before def makes a function asynchronous.",
  },
  {
    question: "What does await do?",
    options: [
      "0. Stops the entire program",
      "1. Blocks the thread completely",
      "2. Pauses coroutine and allows other tasks to run",
      "3. Ends the function",
    ],
    answer: 2,
    explanation:
      "await pauses the current coroutine but lets the event loop run other tasks.",
  },
  {
    question: "What happens if you use await outside an async function?",
    options: [
      "0. Works normally",
      "1. Ignored",
      "2. SyntaxError",
      "3. Returns None",
    ],
    answer: 2,
    explanation: "await can only be used inside async functions.",
  },
  {
    question: "What is asyncio.run() mainly responsible for?",
    options: [
      "0. Creating threads",
      "1. Starting and managing the event loop",
      "2. Sleeping",
      "3. Stopping Python",
    ],
    answer: 1,
    explanation: "asyncio.run() starts the event loop and runs the coroutine.",
  },
  {
    question: "What type is returned when calling an async function?",
    options: ["0. string", "1. int", "2. coroutine", "3. None"],
    answer: 2,
    explanation: "Calling an async function returns a coroutine object.",
  },
  {
    question:
      'What will be printed?\nimport asyncio\n\nasync def main():\n    print("Start")\n    await asyncio.sleep(0)\n    print("End")\n\nasyncio.run(main())',
    options: ["0. Start", "1. End", "2. Start then End", "3. Nothing"],
    answer: 2,
    explanation: "Both print statements execute in order.",
  },
  {
    question: "Async programming is best suited for:",
    options: [
      "0. Heavy CPU calculations",
      "1. I/O waiting tasks",
      "2. Encryption",
      "3. Graphics rendering",
    ],
    answer: 1,
    explanation: "Async works best for I/O-bound tasks like network calls.",
  },
  {
    question: "Which module provides async support in Python?",
    options: ["0. threading", "1. multiprocessing", "2. asyncio", "3. time"],
    answer: 2,
    explanation: "The asyncio module provides async functionality.",
  },
  {
    question:
      'What happens here?\nimport asyncio\n\nasync def main():\n    print("A")\n    print("B")\n\nasyncio.run(main())',
    options: ["0. A only", "1. B only", "2. A then B", "3. Error"],
    answer: 2,
    explanation: "Both print statements execute sequentially.",
  },
  {
    question: 'What will happen?\nasync def test():\n    print("Hi")\n\ntest()',
    options: [
      "0. Prints Hi",
      "1. Nothing happens",
      "2. Returns coroutine object",
      "3. Error",
    ],
    answer: 2,
    explanation:
      "Calling async function without running it returns coroutine object.",
  },
  {
    question: "What does asyncio.sleep() do?",
    options: [
      "0. Blocks entire program",
      "1. Non-blocking delay",
      "2. Stops Python",
      "3. Creates thread",
    ],
    answer: 1,
    explanation: "asyncio.sleep is non-blocking and allows other tasks to run.",
  },
  {
    question: "Can you use await inside normal def function?",
    options: [
      "0. Yes always",
      "1. Only in Python 2",
      "2. No",
      "3. Only with threading",
    ],
    answer: 2,
    explanation: "await only works inside async functions.",
  },
  {
    question: "What is a coroutine?",
    options: ["0. A thread", "1. An async function", "2. A loop", "3. A class"],
    answer: 1,
    explanation: "A coroutine is an async function.",
  },
  {
    question: "Async helps improve:",
    options: ["0. Concurrency", "1. CPU power", "2. RAM size", "3. Disk speed"],
    answer: 0,
    explanation:
      "Async improves concurrency by handling multiple waiting tasks.",
  },
  {
    question: "What happens if you forget asyncio.run()?",
    options: [
      "0. Code still runs",
      "1. Coroutine not executed",
      "2. Faster execution",
      "3. Deletes coroutine",
    ],
    answer: 1,
    explanation: "Without asyncio.run(), the coroutine is not executed.",
  },
  {
    question: "Async is primarily single-threaded by default.",
    options: ["0. True", "1. False", "2. Depends on OS", "3. Only in Linux"],
    answer: 0,
    explanation: "Asyncio runs on a single thread using an event loop.",
  },
  {
    question: "Which of these is blocking?",
    options: [
      "0. asyncio.sleep(1)",
      "1. await asyncio.sleep(1)",
      "2. time.sleep(1)",
      "3. asyncio.gather()",
    ],
    answer: 2,
    explanation: "time.sleep blocks the entire thread.",
  },
];
